TestIntant/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TestIntant.Models
{
    public class Category
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        [Required]
        public String Name { get; set; }

        public String Image { get; set; }
    }
}

TestIntant/Models/ViewModels/CategoryView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace TestIntant.Models.ViewModels
{
    public class CategoryView
    {
        [Required]
        public String Name { get; set; }

        public IFormFile Image { get; set; }
    }
}

TestIntant/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestIntant.Data;
using TestIntant.Models;
using TestIntant.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;

namespace TestIntant.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public CategoriesController(ApplicationDbContext context, IHostingEnvironment HostingEnvironment)
        {
            hostingEnvironment = HostingEnvironment;
            _context = context;
        }
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }
                
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryView model)
        {
            if (ModelState.IsValid)
            {
                Category category = new Category();
                category.Name = model.Name;
                if (model.Image != null)
                {
                    var fileName = Path.GetFileName(Convert.ToString(ContentDispositionHeaderValue.Parse(model.Image.ContentDisposition).FileName).Trim('"'));
                    var fileExt = Path.GetExtension(fileName);
                    var path = Path.Combine(this.hostingEnvironment.WebRootPath, "images", category.Id.ToString("N") + fileExt);
                    category.Image = $"/images/{category.Id:N}{fileExt}";
                    using (var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                    {
                        await model.Image.CopyToAsync(fileStream);
                    }
                }
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            ViewBag.ImagePath = category.Image;
            CategoryView model = new CategoryView();
            model.Name = category.Name;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, CategoryView model)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var category = await _context.Categories.SingleOrDefaultAsync(m => m.Id == id);
                    category.Name = model.Name;
                    if (model.Image != null)
                    {
                        if (category.Image != null) System.IO.File.Delete(Path.Combine(hostingEnvironment.WebRootPath, "images", category.Id.ToString("N") + Path.GetExtension(category.Image)));
                        var fileName = Path.GetFileName(Convert.ToString(ContentDispositionHeaderValue.Parse(model.Image.ContentDisposition).FileName).Trim('"'));
                        var fileExt = Path.GetExtension(fileName);
                        var path = Path.Combine(this.hostingEnvironment.WebRootPath, "images", category.Id.ToString("N") + fileExt);
                        category.Image = $"/images/{category.Id:N}{fileExt}";
                        using (var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                        {
                            await model.Image.CopyToAsync(fileStream);
                        }
                    }
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var category1 = await _context.Categories.SingleOrDefaultAsync(m => m.Id == id);
            ViewBag.Id = id;
            ViewBag.ImagePath = category1.Image;
            return View(model);
        }
        
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .SingleOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var category = await _context.Categories.SingleOrDefaultAsync(m => m.Id == id);
            if (category.Image != null) System.IO.File.Delete(Path.Combine(hostingEnvironment.WebRootPath, "images", category.Id.ToString("N") + Path.GetExtension(category.Image)));
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(Guid id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

TestIntant/Controllers/SubcategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestIntant.Data;
using TestIntant.Models;
using TestIntant.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;

namespace TestIntant.Controllers
{
    public class SubcategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public SubcategoriesController(ApplicationDbContext context, IHostingEnvironment HostingEnvironment)
        {
            hostingEnvironment = HostingEnvironment;
            _context = context;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {
            var applicationDbContext = _context.Subcategories.Where(s => s.CategoryId == categoryId).Include(s => s.Category);
            ViewBag.CategoryId = categoryId;
            var category = _context.Categories.SingleOrDefault(c => c.Id == categoryId);
            ViewBag.Category = category.Name;
            return View(await applicationDbContext.ToListAsync());
        }
        
        
        public IActionResult Create(Guid categoryId)
        {
            SubcategoryView model = new SubcategoryView();
            model.CategoryId = categoryId;
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubcategoryView model)
        {
            if (ModelState.IsValid)
            {
                Subcategory subcategory = new Subcategory();
                subcategory.Name = model.Name;
                subcategory.CategoryId = model.CategoryId;
                if (model.Image != null)
                {
                    var fileName = Path.GetFileName(Convert.ToString(ContentDispositionHeaderValue.Parse(model.Image.ContentDisposition).FileName).Trim('"'));
                    var fileExt = Path.GetExtension(fileName);
                    var path = Path.Combine(this.hostingEnvironment.WebRootPath, "images", subcategory.Id.ToString("N") + fileExt);
                    subcategory.Image = $"/images/{subcategory.Id:N}{fileExt}";
                    using (var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                    {
                        await model.Image.CopyToAsync(fileStream);
                    }
                }
                _context.Add(subcategory);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { categoryId = subcategory.CategoryId });
            }
            return View(model);
        }
        
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subcategory = await _context.Subcategories.SingleOrDefaultAsync(m => m.Id == id);
            if (subcategory == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            ViewBag.ImagePath = subcategory.Image;
            SubcategoryView model = new SubcategoryView();
            model.Name = subcategory.Name;
            model.CategoryId = subcategory.CategoryId;
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name", subcategory.CategoryId);
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, SubcategoryView model)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var subcategory = await _context.Subcategories.SingleOrDefaultAsync(m => m.Id == id);
                    subcategory.Name = model.Name;
                    subcategory.CategoryId = model.CategoryId;
                    if (model.Image != null)
                    {
                        if (subcategory.Image != null) System.IO.File.Delete(Path.Combine(hostingEnvironment.WebRootPath, "images", subcategory.Id.ToString("N") + Path.GetExtension(subcategory.Image)));
                        var fileName = Path.GetFileName(Convert.ToString(ContentDispositionHeaderValue.Parse(model.Image.ContentDisposition).FileName).Trim('"'));
                        var fileExt = Path.GetExtension(fileName);
                        var path = Path.Combine(this.hostingEnvironment.WebRootPath, "images", subcategory.Id.ToString("N") + fileExt);
                        subcategory.Image = $"/subcategory/{subcategory.Id:N}{fileExt}";
                        using (var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                        {
                            await model.Image.CopyToAsync(fileStream);
                        }
                    }
                    _context.Update(subcategory);
                    await _context.SaveChangesAsync();
                    var category = await _context.Categories.SingleOrDefaultAsync(c => c.Id == subcategory.CategoryId);
                    return RedirectToAction("Index", new { categoryId = category.Id });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubcategoryExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewBag.Id = id;
            var subcategory1 = _context.Subcategories.SingleOrDefault(s => s.Id == id);
            ViewBag.ImagePath = subcategory1.Image;
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name", subcategory1.CategoryId);
            return View(model);
        }
        
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subcategory = await _context.Subcategories
                .Include(s => s.Category)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (subcategory == null)
            {
                return NotFound();
            }

            return View(subcategory);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var subcategory = await _context.Subcategories.SingleOrDefaultAsync(m => m.Id == id);
            var category = await _context.Categories.SingleOrDefaultAsync(c => c.Id == subcategory.CategoryId);
            if (subcategory.Image != null) System.IO.File.Delete(Path.Combine(hostingEnvironment.WebRootPath, "images", subcategory.Id.ToString("N") + Path.GetExtension(subcategory.Image)));
            _context.Subcategories.Remove(subcategory);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { categoryId = category.Id });
        }

        private bool SubcategoryExists(Guid id)
        {
            return _context.Subcategories.Any(e => e.Id == id);
        }
    }
}

TestIntant/Views/Categories/Create.cshtml
@model TestIntant.Models.ViewModels.CategoryView
@{
    ViewData["Title"] = "Create";
}
<!DOCTYPE html>
<html>
<head>
    <script src="~/js/AddImage.js" asp-append-version="true"></script>
</head>
<body>
    <h2>Новая категория</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="file_upload">
                        <img style="max-height: 300px; max-width: 300px; cursor: pointer" id="upload-img" alt="image" />
                        <input id="upload" type="file" asp-for="Image">
                    </label>
                </div>
                <div class="form-group">
                    <label class="control-label">Название</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-default">Назад</a>
                    <button type="submit" value="Create" class="btn btn-default">Сохранить</button>
                </div>
            </form>
        </div>
    </div>    
</body>
</html>

TestIntant/Views/Categories/Delete.cshtml
@model TestIntant.Models.Category
@{
    ViewData["Title"] = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить эту категорию?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>
        <dd>
            @Model.Name
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <a class="btn btn-default" asp-action="Index">Назад</a>
        <input type="submit" value="Удалить" class="btn btn-default" />
    </form>
</div>

TestIntant/Views/Categories/Edit.cshtml
@model TestIntant.Models.ViewModels.CategoryView

@{
    ViewData["Title"] = "Edit";
}
<!DOCTYPE html>
<html>
<head>
    <script src="~/js/AddImage.js" asp-append-version="true"></script>
</head>
<body>
    <h2>Редактировать категорию</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post" enctype="multipart/form-data" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="file_upload">
                        <img style="max-height: 300px; max-width: 300px; cursor: pointer" src="@ViewBag.ImagePath" id="upload-img" alt="image" />
                        <input id="upload" type="file" asp-for="Image">
                    </label>
                </div>
                <div class="form-group">
                    <label class="control-label">Название</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-default">Назад</a>
                    <button type="submit" class="btn btn-default" asp-route-id="@ViewBag.Id">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

TestIntant/Views/Categories/Index.cshtml
@model IEnumerable<TestIntant.Models.Category>

@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <h2>Товары</h2>
    <p>
        <a class="btn btn-default" asp-action="Create">Добавить категорию</a>
    </p>
    <hr />
    <row>
        @foreach (var item in Model)
        {
            <div class="col-lg-3" style="padding: 40px">
                <img src="@item.Image" style="max-height: 200px; max-width: 200px;" alt="Image" />
                <div style="font-size:18px; text-align: center; margin: 10px 0 10px">
                    <a asp-controller="Subcategories" asp-action="Index" asp-route-categoryId="@item.Id">@item.Name</a>
                </div>
                <a class="btn btn-default" asp-action="Edit" asp-route-id="@item.Id">
                    <span title="Редактировать" class="glyphicon glyphicon-edit"></span>
                </a>
                <a class="btn btn-default" asp-action="Delete" asp-route-id="@item.Id">
                    <span title="Удалить" class="glyphicon glyphicon-trash"></span>
                </a>
            </div>
        }
    </row>            
</body>
</html>